services:
  db:
    image: postgres:16-alpine
    container_name: db_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-steam_dbt}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-steam_dbt}"]
      interval: 5s
      timeout: 5s
      retries: 5

  dbt:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: steam_dbt_cont
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_PORT=5432
      - DB_NAME=${DB_NAME:-steam_dbt}
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: